rtl/common/round_shift.v
rtl/common/saturate_int8.v
rtl/cnn/requant_activation_unit.v
rtl/cnn/systolic_pe.v
rtl/cnn/pw_systolic_array_8x8.v
rtl/cnn/dw_line_buffer.v
rtl/cnn/dw_window_generator.v
rtl/cnn/dw_mac_lanes.v
rtl/cnn/dw_tile_buffer.v
rtl/cnn/dw_tile_fusion_engine.v
rtl/cnn/conv3x3_stem_engine.v
rtl/cnn/gap_unit.v
rtl/cnn/fc_unit.v
rtl/cnn/tile_scheduler.v
rtl/cnn/feature_sram_bank.v
rtl/cnn/feature_sram_pingpong.v
rtl/cnn/ds_block_tile_engine.v
rtl/cnn/status_counter.v
rtl/cnn/descriptor_fetch.v
rtl/cnn/cnn_layer_runner.v
rtl/cnn/cnn_top_ctrl.v
rtl/cnn/cnn_top.v
rtl/cpu_if/rv_cnn_custom_if.v
rtl/cpu_if/npc_cnn_custom_bridge.v
rtl/cpu_if/cnn_mmio_regs.v
rtl/npc/vsrc/stages/pc_reg.v
rtl/npc/vsrc/stages/reg_file.v
rtl/npc/vsrc/stages/ctrl_unit.v
rtl/npc/vsrc/stages/imm_gen.v
rtl/npc/vsrc/stages/alu.v
rtl/npc/vsrc/stages/branch_cond.v
rtl/npc/vsrc/hazard/forward_unit.v
rtl/npc/vsrc/hazard/hazard_unit.v
rtl/npc/vsrc/pip_regs/reg_if_id.v
rtl/npc/vsrc/pip_regs/reg_id_ex.v
rtl/npc/vsrc/pip_regs/reg_ex_mem.v
rtl/npc/vsrc/pip_regs/reg_mem_wb.v
rtl/npc/vsrc/rv_core.v
