#!/usr/bin/env python3
"""Generate firmware model headers from the int8 smoke NPZ export."""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np


DS_SPECS = [
    (1, 16, 32),
    (2, 32, 64),
    (3, 64, 64),
    (4, 64, 128),
    (5, 128, 128),
    (6, 128, 256),
]


def flat_values(model: np.lib.npyio.NpzFile, key: str, dtype: np.dtype) -> list[int]:
    return np.asarray(model[key], dtype=dtype).reshape(-1).astype(np.int64).tolist()


def scalar_i32(model: np.lib.npyio.NpzFile, key: str, default: int = 0) -> int:
    if key not in model:
        return default
    return int(np.asarray(model[key], dtype=np.int32).reshape(()))


def write_array(
    lines: list[str],
    c_type: str,
    name: str,
    values: list[int],
    columns: int = 12,
    const: bool = True,
) -> None:
    const_kw = "const " if const else ""
    lines.append(f"static {const_kw}{c_type} {name}[{len(values)}] = {{")
    for start in range(0, len(values), columns):
        chunk = values[start : start + columns]
        lines.append("    " + ", ".join(str(int(v)) for v in chunk) + ",")
    lines.append("};")
    lines.append("")


def write_bss_array(lines: list[str], c_type: str, name: str, count: int) -> None:
    lines.append(f"static {c_type} {name}[{count}];")


def generate_weights_h(model: np.lib.npyio.NpzFile, path: Path) -> None:
    packed_arrays: list[tuple[str, str, list[int]]] = [
        ("int8_t", "g_model_input_image_i8_packed", flat_values(model, "input_image_i8", np.int8)),
        ("int8_t", "g_stem_weight_i8_packed", flat_values(model, "stem_weight", np.int8)),
        ("int8_t", "g_fc_weight_i8_packed", flat_values(model, "fc_weight", np.int8)),
    ]
    for idx, _, _ in DS_SPECS:
        packed_arrays.append(( "int8_t", f"g_ds{idx}_dw_weight_i8_packed", flat_values(model, f"ds{idx}_dw_weight", np.int8)))
        packed_arrays.append(( "int8_t", f"g_ds{idx}_pw_weight_i8_packed", flat_values(model, f"ds{idx}_pw_weight", np.int8)))

    lines: list[str] = [
        "#ifndef MODEL_WEIGHTS_H",
        "#define MODEL_WEIGHTS_H",
        "",
        "#include <stdint.h>",
        "",
        "/* Generated by python/export_firmware_headers.py.",
        " * v1 accelerator memory format uses one int8 element per int32 word.",
        " * Packed int8 constants live in ROM and are expanded into word buffers",
        " * before descriptors are launched.",
        " */",
        "",
        "#define MODEL_EXPORTED_SMOKE_MODEL 1",
        "",
    ]

    write_bss_array(lines, "int32_t", "g_model_input_image_words", 32 * 32 * 3)
    write_bss_array(lines, "int32_t", "g_stem_weight_words", 16 * 27)
    for idx, in_c, out_c in DS_SPECS:
        write_bss_array(lines, "int32_t", f"g_ds{idx}_dw_weight_words", in_c * 9)
        write_bss_array(lines, "int32_t", f"g_ds{idx}_pw_weight_words", out_c * in_c)
    write_bss_array(lines, "int32_t", "g_fc_weight_words", 10 * 256)
    lines.append("")

    for c_type, name, values in packed_arrays:
        write_array(lines, c_type, name, values, columns=16, const=True)

    lines.extend(
        [
            "static void model_expand_i8_words(int32_t *dst, const int8_t *src, uint32_t count)",
            "{",
            "    uint32_t i;",
            "",
            "    for (i = 0; i < count; i++) {",
            "        dst[i] = (int32_t)src[i];",
            "    }",
            "}",
            "",
            "static void edgedscnet_c10_init_payload(void)",
            "{",
            "    model_expand_i8_words(g_model_input_image_words, g_model_input_image_i8_packed, 32u * 32u * 3u);",
            "    model_expand_i8_words(g_stem_weight_words, g_stem_weight_i8_packed, 16u * 27u);",
        ]
    )
    for idx, in_c, out_c in DS_SPECS:
        lines.append(
            f"    model_expand_i8_words(g_ds{idx}_dw_weight_words, "
            f"g_ds{idx}_dw_weight_i8_packed, {in_c}u * 9u);"
        )
        lines.append(
            f"    model_expand_i8_words(g_ds{idx}_pw_weight_words, "
            f"g_ds{idx}_pw_weight_i8_packed, {out_c}u * {in_c}u);"
        )
    lines.extend(
        [
            "    model_expand_i8_words(g_fc_weight_words, g_fc_weight_i8_packed, 10u * 256u);",
            "}",
            "",
            "#endif",
        ]
    )
    path.write_text("\n".join(lines) + "\n", encoding="ascii")


def generate_quant_h(model: np.lib.npyio.NpzFile, path: Path) -> None:
    lines: list[str] = [
        "#ifndef MODEL_QUANT_H",
        "#define MODEL_QUANT_H",
        "",
        "#include <stdint.h>",
        "",
        "/* Generated by python/export_firmware_headers.py. */",
        "",
    ]

    input_zp = scalar_i32(model, "input_zero_point", 0)
    stem_ozp = scalar_i32(model, "stem_output_zero_point", 0)
    lines.append(f"static const int32_t g_model_input_zero_point = {input_zp};")
    lines.append(f"static const int32_t g_stem_output_zero_point = {stem_ozp};")
    prev_zp = stem_ozp
    for idx, _, _ in DS_SPECS:
        dw_zp = scalar_i32(model, f"ds{idx}_dw_output_zero_point", 0)
        pw_zp = scalar_i32(model, f"ds{idx}_pw_output_zero_point", 0)
        lines.append(f"static const int32_t g_ds{idx}_input_zero_point = {prev_zp};")
        lines.append(f"static const int32_t g_ds{idx}_dw_output_zero_point = {dw_zp};")
        lines.append(f"static const int32_t g_ds{idx}_pw_output_zero_point = {pw_zp};")
        prev_zp = pw_zp
    lines.append(f"static const int32_t g_fc_output_zero_point = {scalar_i32(model, 'fc_output_zero_point', 0)};")
    lines.append("")

    write_array(lines, "int32_t", "g_stem_bias", flat_values(model, "stem_bias", np.int32), columns=8)
    write_array(lines, "int32_t", "g_stem_mul", flat_values(model, "stem_multiplier", np.int32), columns=4)
    write_array(lines, "int32_t", "g_stem_shift_words", flat_values(model, "stem_shift", np.int32), columns=8)

    for idx, _, _ in DS_SPECS:
        write_array(lines, "int32_t", f"g_ds{idx}_dw_bias", flat_values(model, f"ds{idx}_dw_bias", np.int32), columns=8)
        write_array(lines, "int32_t", f"g_ds{idx}_dw_mul", flat_values(model, f"ds{idx}_dw_multiplier", np.int32), columns=4)
        write_array(lines, "int32_t", f"g_ds{idx}_dw_shift_words", flat_values(model, f"ds{idx}_dw_shift", np.int32), columns=8)
        write_array(lines, "int32_t", f"g_ds{idx}_pw_bias", flat_values(model, f"ds{idx}_pw_bias", np.int32), columns=8)
        write_array(lines, "int32_t", f"g_ds{idx}_pw_mul", flat_values(model, f"ds{idx}_pw_multiplier", np.int32), columns=4)
        write_array(lines, "int32_t", f"g_ds{idx}_pw_shift_words", flat_values(model, f"ds{idx}_pw_shift", np.int32), columns=8)

    write_array(lines, "int32_t", "g_fc_bias", flat_values(model, "fc_bias", np.int32), columns=8)
    write_array(lines, "int32_t", "g_fc_mul", flat_values(model, "fc_multiplier", np.int32), columns=4)
    write_array(lines, "int32_t", "g_fc_shift_words", flat_values(model, "fc_shift", np.int32), columns=8)

    lines.append("#endif")
    path.write_text("\n".join(lines) + "\n", encoding="ascii")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--npz", type=Path, default=Path("build/model_export/edgedscnet_c10_int8_smoke.npz"))
    parser.add_argument("--model-dir", type=Path, default=Path("sw/model"))
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    args.model_dir.mkdir(parents=True, exist_ok=True)
    with np.load(args.npz, allow_pickle=True) as model:
        generate_weights_h(model, args.model_dir / "model_weights.h")
        generate_quant_h(model, args.model_dir / "model_quant.h")
    print(f"wrote {args.model_dir / 'model_weights.h'}")
    print(f"wrote {args.model_dir / 'model_quant.h'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
